// STUDENTS

### 
GET http://localhost:3003/students?name=rick
###
POST http://localhost:3003/students
Content-Type: application/json

{
 "name": "Teste da Glorria Eterna",
  "email": "teste@g1a1aaaaaa1aaa111maiqlll.com",
  "birthDate": "02/01/2020",
  "classId": "108dce73-ca6a-499f-a963-25ec4e0b65a6"
}

###
PUT http://localhost:3003/students
Content-Type: application/json

{
 "studentId": "0a9e2176-da13-4e9f-b15e-ac4dd7e503a3",
 "idClass": "108dce73-ca6a-499f-a963-25ec4e0b65a6"
}

//*================================================================================

// CLASS

### 
GET http://localhost:3003/class?name=Heley


###
POST http://localhost:3003/class
Content-Type: application/json

{
 "name": "Teste Eterna 2",
 "modules": 2
}

###
PUT http://localhost:3003/class/108dce73-ca6a-499f-a963-25ec4e0b65a6
Content-Type: application/json

{
 "modules": 2
}

// ============================================================================

// TEACHERS

###
GET http://localhost:3003/teachers

###
POST http://localhost:3003/teachers
Content-Type: application/json

{
 "name": "Nicolas Tesla",
  "email": "nicolastesla@gmail.com",
  "birthDate": "02/01/1899",
  "classId": "108dce73-ca6a-499f-a963-25ec4e0b65a6"
}

    
